# Práctica de la librería Numpy

En este notebook, se desarrollarán una serie de tareas utilizando la librería Numpy (Numerical Python).

Se proponen y documentan posibles formas de resolver los ejercicios, pero las mismas no son únicas.

Siempre es una buena idea verificar la [Documentación Oficial de Numpy](https://numpy.org/devdocs/user/index.html), donde es posible encontrar todo tipo de información referida a esta librería. Y si te quedas trabado, busca en Google "como hacer [algo] con Numpy". Hay enormes probabilidades de que esa pregunta ya haya sido respondida!

In [3]:
# Importamos Numpy con su abreviación "np"
import numpy as np

In [9]:
# Podemos crear arrays de una dimensión con la función np.array()
array_unidim = np.array([1,2,3,4,5])
# O un array de dos dimensiones (bidimensional)
array_bidim = np.array([[1,2,3],[4,5,6]])
# O un array de tres dimensiones (tridimensional)
array_tridim = np.array([[[1,2,3],[4,5,6]],[[7,8,6],[10,11,12]]])

Para cada uno de estos arrays, podemos obtener sus propiedades, tales como su "forma", número de dimensiones, tipos de datos y tamaño.

In [5]:
# Atributos del array unidimensional (forma, número de dimensiones, tipos de datos, tamaño, y tipo)
array_unidim.shape, array_unidim.ndim, array_unidim.dtype, array_unidim.size, type(array_unidim)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [10]:
# Atributos del array bidimensional
array_bidim.shape, array_bidim.ndim, array_bidim.dtype, array_bidim.size, type(array_bidim)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [11]:
# Atributos del array tridimensional
array_tridim.shape, array_tridim.ndim, array_tridim.dtype, array_tridim.size, type(array_tridim)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [13]:
# Importamos pandas como pd, y creamos un DataFrame a partir del array bidimensional
import pandas as pd

datos = pd.DataFrame(array_bidim)
datos

0  1  2
0  1  2  3
1  4  5  6

In [16]:
# Creamos un array de tamaño 4x3, formado únicamente por unos (1)
unos = np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# Creamos un array de tamaño 2x4x3, formado únicamente por ceros (0)
ceros = np.zeros((2,4,3))
ceros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
# Creamos un array de números en el rango de 0 a 100, con un paso de 5
array_1 = np.arange(0, 101, 5)
array_1

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [26]:
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (2, 5)
array_2 = np.random.randint(0, 10, (2, 5))
array_2

array([[2, 6, 6, 8, 0],
       [9, 2, 1, 7, 8]])

In [29]:
# Creamos un array de números aleatorios decimales comprendidos en entre 0 y 1, de tamaño (3, 5)
array_3 = np.random.random((3, 5))
array_3

array([[0.17608829, 0.19897516, 0.10768515, 0.56886678, 0.17925065],
       [0.12052043, 0.69182245, 0.46165141, 0.72234166, 0.17041567],
       [0.82733237, 0.6622619 , 0.46095709, 0.66265096, 0.78524192]])

In [30]:
# Establecemos la "semilla" de números aleatorios en 27
np.random.seed(27)
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (3, 5)
array_4 = np.random.randint(0,10,(3,5))
array_4

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

¿Qué ocurre al correr la última celda nuevamente, a diferencia de las anteriores?

In [31]:
# Encontramos los valores únicos del array_4
np.unique(array_4)


array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [33]:
# Extraemos el elemento de índice 1 del array_4
array_4[1]


array([5, 8, 9, 1, 2])

In [34]:
# Extraemos las primeras dos filas del array_4
array_4[:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [35]:
# Extraemos los dos primeros datos de las primeras dos filas del array_4
array_4[:2, :2]

array([[3, 8],
       [5, 8]])

In [38]:
# Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
array_5 = np.random.randint(0,10, (3, 4))
array_6 = np.ones((3,4))


In [39]:
# invocamos el array_5
array_5

array([[1, 1, 7, 0],
       [7, 8, 4, 9],
       [0, 4, 7, 0]])

In [40]:
# invocamos el array_6
array_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
# Sumamos los dos arrays
array_5 + array_6

array([[ 2.,  2.,  8.,  1.],
       [ 8.,  9.,  5., 10.],
       [ 1.,  5.,  8.,  1.]])

In [42]:
# Creamos ahora un array de tamaño (4,3) lleno de unos
array_7 = np.ones((4,3))
array_7

In [43]:
# Intentaremos sumar los arrays 6 y 7 (no se puede porque las dimensiones son distintas)
array_6 + array_7

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

¿A qué se debe el error anterior? ¿Qué deberíamos tener en cuenta para que no suceda? (no se puede porque las dimensiones son distintas) (3,4) (4,3)

In [44]:
# Entonces crearemos otro array de tamaño (4,3) lleno de unos
array_8 = np.ones((4, 3))
array_8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
# Restamos el array_8 al array_7
array_8 - array_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
# Creamos otros dos arrays de tamaño 3x3 con números aleatorios del 1 al 5
array_9 = np.random.randint(1, 5,(3, 3))
array_10 = np.random.randint(1,5,(3, 3))

In [48]:
# invocamos el array_9
array_9

array([[2, 4, 2],
       [3, 3, 1],
       [4, 4, 1]])

In [49]:
# invocamos el array_10
array_10

array([[4, 2, 2],
       [2, 1, 2],
       [2, 2, 3]])

In [50]:
# Multiplicamos los últimos dos arrays entre sí
array_9 * array_10

array([[8, 8, 4],
       [6, 3, 2],
       [8, 8, 3]])

In [51]:
# Elevamos el array_9 al cuadrado
array_9**2

array([[ 4, 16,  4],
       [ 9,  9,  1],
       [16, 16,  1]])

In [52]:
# Buscamos la raíz cuadrada del array_10
np.sqrt(array_10)

array([[2.        , 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.73205081]])

In [53]:
# Hallamos el promedio de los valores del array_9
array_9.mean()


2.6666666666666665

In [54]:
# Hallamos el valor máximo de los valores del array_9
array_9.max()

4

In [55]:
# Hallamos el valor mínimo de los valores del array_9
array_9.min()

1

In [56]:
# Cambiamos la forma del array_9 por una de 9x1, y lo almacenamos como array_11
array_11 = array_9.reshape((9, 1))

In [57]:
# invocamos el array_11
array_11

array([[2],
       [4],
       [2],
       [3],
       [3],
       [1],
       [4],
       [4],
       [1]])

In [59]:
# Transponemos el array_11
array_11.T

array([[2, 4, 2, 3, 3, 1, 4, 4, 1]])

In [62]:
# Comparamos el array_9 y el array_10, para saber cuáles elementos del array_9 son mayores a los del array_10
array_12 = array_9 > array_10

¿Qué tipos de datos forman parte del array de resultados?

In [61]:
# Veamos sus nuevos tipos de datos
array_12.dtype

dtype('bool')

In [63]:
# Alguno de los elementos del array_9 es igual su equivalente del array_10?
array_9 == array_10

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [66]:
# Comparamos nuevamente ambos arrays, en esta ocasión con >=
array_9 >= array_10

array([[False,  True,  True],
       [ True,  True, False],
       [ True,  True, False]])

In [65]:
# Buscamos los elementos del array_9 que son mayores a 2
array_9 > 2

array([[False,  True, False],
       [ True,  True, False],
       [ True,  True, False]])

In [64]:
# Ordenamos de menor a mayor los elementos dentro del array_9
np.sort(array_9)

array([[2, 2, 4],
       [1, 3, 3],
       [1, 4, 4]])